name: user
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^1.0.3
  get: ^4.6.6
  percent_indicator: ^4.2.2
  shared_preferences: ^2.0.15
  firebase_analytics: ^10.10.6
  firebase_core: ^2.31.1
  google_sign_in: ^6.1.0
  firebase_auth: ^4.19.6
  connectivity_plus: ^4.0.2
  #  flutter_facebook_auth: ^3.5.3
  #  flutter_facebook_login: ^3.0.0
  flutter_login_facebook: ^1.4.1
  dio: ^5.3.2
  permission_handler: ^10.4.3
  image_picker: ^1.0.2
  image_cropper: ^5.0.0
  flutter_image_compress: ^2.0.4
  email_validator: ^2.0.1
  mobile_number: ^2.1.1
  sms_autofill: ^2.3.1
  material_design_icons_flutter: ^7.0.7296
  geolocator: ^9.0.2
  geocoding: ^2.0.4
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  font_awesome_flutter: ^10.1.0
  razorpay_flutter: ^1.3.4
  flutter_paystack:
    git:
      url: https://github.com/I-driod/flutter_paystack.git
      ref: master
  carousel_slider: ^4.1.1
  dots_indicator: ^3.0.0
  firebase_messaging: ^14.9.3
  flutter_local_notifications: ^15.1.0+1
  flutter_html: ^3.0.0-beta.2
  url_launcher: ^6.1.2
  google_maps_flutter: ^2.1.5
  flutter_mapbox_autocomplete:
    git:
      url: https://github.com/thiagoadriano/flutter_mapbox_autocomplete.git
  mapbox_search: ^3.0.1+2
  flutter_rating_bar: ^4.0.1
  share_plus: ^7.1.0
  photo_view: ^0.14.0
  flutter_polyline_points_plus: ^3.0.0
  badges: ^3.0.2
  flutter_barcode_scanner: ^2.0.0
  sign_in_with_apple: ^5.0.0
  cloud_firestore: ^4.8.4
  firebase_storage: ^11.0.11
  timelines: ^0.1.0
  readmore: 2.2.0
  marquee: ^2.2.3
  flutter_speed_dial: ^7.0.0
  provider: 6.0.5

dependency_overrides:
  intl: ^0.18.0
  http: ^1.1.0
  fading_edge_scrollview: ^4.1.1 # This is necessary because marquee package is not updated

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  change_app_package_name: ^1.1.0

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^4.0.0

flutter_icons:
  android: "ic_launcher"
  ios: false
  image_path: "assets/images/icon.png"


flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/
    - assets/images/


  fonts:
    - family: Google-Sans
      fonts:
        - asset: assets/fonts/ProductSans-Regular.ttf